version: '3.9'

services:
  db:
    image: postgres:16beta1-alpine3.18
    container_name: db
    restart: unless-stopped
    networks:
        - backend
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: ax2
    ports:
      - "5432:5432"

networks:
    backend:
        name: backend
        internal: false # in production, it should be true if you don't want to expose this network to the outside world
        driver: bridge